backend:
  name: git-gateway
  repo: stephangriesel/hlokomela-site
  branch: latest
  identity_url: https://auth.decapbridge.com/sites/4ad973b2-3e28-4dc1-9b5c-1681eb6115e2
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} {{slug}} - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} {{slug}} - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} {{slug}} - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload {{path}} - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete {{path}} - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

site_url: https://hlokomela-site.pages.dev
media_folder: public/upload
public_folder: /upload
logo_url: https://res.cloudinary.com/stephangriesel/image/upload/v1687318146/logo_cqhhz9.png

collections:
  - name: media
    label: Media
    label_singular: Media Post
    folder: src/pages/media
    create: true
    delete: true
    sortable_fields: [commit_date, title, "language.en"]
    fields:
      - { name: title, widget: string, label: Post Title }
      - { name: pdfFile, widget: file, label: PDF File, required: false, accept: ["application/pdf"] }
      - name: layout
        widget: select
        default: "../../layouts/BlogPost.astro"
        options:
          - { label: General, value: "../../layouts/BlogPost.astro" }

  - name: forms
    label: Forms
    label_singular: Form Post
    folder: src/pages/forms
    create: true
    delete: true
    sortable_fields: [commit_date, title, "language.en"]
    fields:
      - { name: title, widget: string, label: Post Title }
      - { name: pdfFile, widget: file, label: PDF File, required: false, accept: ["application/pdf"] }
      - name: layout
        widget: select
        default: "../../layouts/BlogPost.astro"
        options:
          - { label: General, value: "../../layouts/BlogPost.astro" }

  - name: annualreports
    label: Annual Reports
    label_singular: Annual Report
    folder: src/pages/annualreports
    create: true
    delete: true
    sortable_fields: [commit_date, title, "language.en"]
    fields:
      - { name: title, widget: string, label: Post Title }
      - { name: pdfFile, widget: file, label: PDF File, required: false, accept: ["application/pdf"] }
      - name: layout
        widget: select
        default: "../../layouts/BlogPost.astro"
        options:
          - { label: General, value: "../../layouts/BlogPost.astro" }

  - name: articlelinks
    label: Article Links
    label_singular: Article Link
    folder: src/pages/articlelinks
    create: true
    delete: true
    sortable_fields: [publishDate, commit_date, title, "language.en"]
    fields:
      - { name: title, widget: string, label: Post Title }
      - { name: link, widget: string, label: Article Link }
      - name: publishDate
        widget: datetime
        label: Year
        format: "YYYY-MM-DD"
        date_format: "YYYY"
        time_format: false
        picker_utc: true
        hint: Used to sort articles newest to oldest. Only the year matters.
      - name: layout
        widget: select
        default: "../../layouts/BlogPost.astro"
        options:
          - { label: General, value: "../../layouts/BlogPost.astro" }

  - name: site_content
    label: Site Content
    files:
      - name: homepage
        label: Homepage Text
        file: src/content/homepage.md
        fields:
          - { name: whoWeAreText, widget: text, label: "Who We Are - Paragraph" }
          - { name: whoWeBecameText, widget: text, label: "Who We Became - Paragraph" }
      - name: adverts
        label: Press & Media Adverts
        file: src/content/adverts.md
        fields:
          - { name: healthcard, widget: image, label: Health Card Advert }
          - { name: fluvaccine, widget: image, label: Flu Vaccine Advert }

  - name: projectvideos
    label: Project Videos
    label_singular: Project Video
    folder: src/pages/projectvideos
    create: true
    delete: true
    sortable_fields: [commit_date, title, "language.en"]
    fields:
      - { name: title, widget: string, label: Post Title }
      - { name: embeddedVideo, widget: string, label: YouTube ID }
      - name: layout
        widget: select
        default: "../../layouts/BlogPost.astro"
        options:
          - { label: General, value: "../../layouts/BlogPost.astro" }
